/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v2/ascella/config": {
    /** Returns the upload config of the given auth token */
    get: {
      parameters: {
        query: {
          auth: string;
        };
      };
    };
  };
  "/v2/ascella/domain": {
    /** set the domain of the user */
    post: {
      responses: {
        /** Created */
        201: {
          content: {
            "application/json": components["schemas"]["SendMessage"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["DomainData"];
        };
      };
    };
  };
  "/v2/ascella/domains": {
    /** Returns all ascella domains */
    get: {
      responses: {
        /** Created */
        201: {
          content: {
            "application/json": components["schemas"]["Domain"][];
          };
        };
      };
    };
  };
  "/v2/ascella/embed": {
    /** set the embed of the user */
    post: {
      responses: {
        /** Created */
        201: {
          content: {
            "application/json": components["schemas"]["SendMessage"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["EmbedData"];
        };
      };
    };
  };
  "/v2/ascella/images": {
    /** View the images of a user */
    post: {
      responses: {
        /** Created */
        201: {
          content: {
            "application/json": components["schemas"]["SimpleImages"][];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["QueryData"];
        };
      };
    };
  };
  "/v2/ascella/language.json": {
    /** Get a language file of ascella */
    get: {
      parameters: {
        query: {
          lang?: string;
        };
      };
      responses: {
        /** Created */
        201: {
          content: {
            "application/json": components["schemas"]["LanguagesResponse"];
          };
        };
      };
    };
  };
  "/v2/ascella/public": {
    /** Make a image public this endpoint is useless atm */
    post: {
      responses: {
        /** Created */
        201: {
          content: {
            "application/json": components["schemas"]["SendMessage"];
          };
        };
      };
    };
  };
  "/v2/ascella/redirect": {
    /** Used to create redirects */
    post: {
      responses: {
        /** Created */
        201: {
          content: {
            "application/json": components["schemas"]["SendMessage"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RedirectData"];
        };
      };
    };
  };
  "/v2/ascella/reviews.json": {
    /** Get ascella reviews! */
    get: {
      responses: {
        /** Created */
        201: {
          content: {
            "application/json": components["schemas"]["Comment"][];
          };
        };
      };
    };
  };
  "/v2/ascella/stats.json": {
    /** provides some cool stats about ascella to use somewhere */
    get: {
      responses: {
        /** Created */
        201: {
          content: {
            "application/json": components["schemas"]["AscellaStats"];
          };
        };
      };
    };
  };
  "/v2/ascella/upload": {
    /** Upload a image to ascella */
    post: {
      responses: {
        /** Created */
        201: {
          content: {
            "application/json": components["schemas"]["UploadSuccess"];
          };
        };
      };
      requestBody: {
        content: {
          "multipart/form-data": {
            /** Format: binary */
            file_data: string;
          };
        };
      };
    };
  };
  "/v2/ascella/upload_style": {
    /** set the domain of the user */
    post: {
      responses: {
        /** Created */
        201: {
          content: {
            "application/json": components["schemas"]["SendMessage"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UploadStyleData"];
        };
      };
    };
  };
  "/v2/ascella/verify": {
    /** Used to check if a user is verified */
    post: {
      responses: {
        /** Created */
        201: {
          content: {
            "*/*": components["schemas"]["Users"];
          };
        };
      };
    };
  };
  "/v2/ascella/view/{image}.{ext:(gif|webp|jpg|jpeg|png)$}": {
    /** View a image uploaded to ascella */
    get: {
      parameters: {
        path: {
          image: string;
          "ext:(gif|webp|jpg|jpeg|png)$": string;
        };
      };
    };
  };
  "/v2/ascella/view/{image}/stats": {
    /** View the stats & info of an image */
    get: {
      parameters: {
        path: {
          image: string;
        };
      };
      responses: {
        /** Created */
        201: {
          content: {
            "application/json": components["schemas"]["StatsResponse"];
          };
        };
      };
    };
  };
}
export type Structs = components["schemas"]
export type User = Structs["Users"];
export interface components {
  schemas: {
    AscellaStats: {
      /**
       * @description THe commit hash used by ascella
       * @example https://github.com/ascellahost/tsunami/commit/e968eb666fa3b0ea974248c30931a9210919fd44
       */
      commit_hash: string;
      /**
       * Format: int64
       * @description The unix timestamp ascella was created
       * @example 1629305469
       */
      created_date: number;
      /**
       * Format: int32
       * @description The api version twilight uses
       * @example 10
       */
      discord_api_version: number;
      /** @description If ascella is fast obviously */
      fast: boolean;
      /**
       * @description Rustc info
       * @example rustc 1.62.0-nightly (4c60a0ea5 2022-05-04)
       */
      rustc: string;
      /**
       * Format: int64
       * @description The amount of domains ascella has use the domains endpoint to find out
       *  which
       * @example 17
       */
      total_domains: number;
      /**
       * Format: int64
       * @description Total amount of images uploade to ascella  (includes redirects)
       * @example 6441
       */
      total_uploads: number;
      /**
       * Format: int64
       * @description Amount of userst that ran /redeem
       * @example 100
       */
      total_users: number;
      /**
       * Format: int64
       * @description Total amount of views a image has
       * @example 87545
       */
      total_views: number;
      /** @description Size of uploads currently broken :( */
      upload_size: string;
      /**
       * @description Ascella uptime - since last restart for update
       * @example 1day 10h 7m 42s 572ms 387us 449ns
       */
      uptime: string;
      /**
       * @description Memory usage by the rust process
       * @example 56.89 MB
       */
      usage: string;
    };
    Comment: {
      /** @example https://cdn.discordapp.com/embed/avatars/5.png */
      avatar: string;
      /** @example havent heard any voices since i started using ascella! */
      comment: string;
      /** @example Deleted User */
      name: string;
    };
    /**
     * @description Domain
     *
     *  A single domain in a domain vector
     */
    Domain: {
      /** @description Weather or not this is a apex domain */
      apex: boolean;
      /** @example Ascella.host */
      domain: string;
      /**
       * Format: int32
       * @description Id of the user who owns this domain
       */
      owner: number;
    };
    /**
     * @description DomainData
     *
     *  Set your new domain here!
     */
    DomainData: {
      domain: string;
    };
    /**
     * @description EmbedData
     *
     *  Data for the embed
     */
    EmbedData: {
      /** @example Some author */
      author?: string;
      /** @example #5f8f91 */
      color?: string;
      /** @example This is a image */
      description?: string;
      link?: string;
      /** @example Hi */
      title?: string;
      url?: string;
    };
    LanguagesResponse: {
      data: { [key: string]: unknown };
    };
    /**
     * @description QueryData
     *
     *  The data required to view stuff
     */
    QueryData: {
      /** Format: int32 */
      skip: number;
    };
    /**
     * @description RedirectData
     *
     *  Set the redirect
     */
    RedirectData: {
      /** @example https://google.com */
      to: string;
      /** @example google */
      vanity: string;
    };
    SendMessage: {
      /**
       * Format: int32
       * @example 200
       */
      code: number;
      /** @example Succesful Response */
      message: string;
      success: boolean;
    };
    SimpleImages: {
      /** Format: int32 */
      id: number;
      vanity: string;
    };
    /** @description View stats of a image */
    StatsResponse: {
      content_type: string;
      embed?: {
        color?: string;
        description?: string;
        title?: string;
        url?: string;
      };
      /** Format: int32 */
      id: number;
      image_size?: string;
      redirect?: string;
      /** Format: int32 */
      user_id: number;
      user_name: string;
      /** Format: int32 */
      views: number;
    };
    /**
     * @description UploadStyleData
     *
     *  Set your new domain here!
     */
    UploadStyleData: {
      /** Format: int32 */
      style: number;
    };
    UploadSuccess: {
      /**
       * Format: int32
       * @example 200
       */
      code: number;
      /** @example https://ascella.wtf/v2/ascella/view/tdaCZHo1.png */
      raw: string;
      /** @example true */
      success: boolean;
      /** @example https://ascella.host/tdaCZHo1 */
      url: string;
    };
    Users: {
      /** Format: int32 */
      autodelete?: number;
      /** Format: int32 */
      deleteall?: number;
      discord_id: string;
      domain: string;
      /** Format: int32 */
      flags: number;
      /** Format: int32 */
      id: number;
      invite_code?: string;
      /** Format: int32 */
      invited_by: number;
      key: string;
      lang: string;
      name: string;
      upload_key?: string;
      /** Format: int32 */
      url_style: number;
    };
  };
}

export interface operations { }

export interface external { }
